List favorites = [
  "John",
  "Mary",
  "Cherry",
  "Millicent",
  "Davie",
  "John",
  "Mary",
  "Cherry",
  "Millicent",
  "Davie",
  "John",
  "Mary",
  "Cherry",
  "Millicent",
  "Davie"
];
List<String> images = [
  "assets/images/user0.png",
  "assets/images/user1.png",
  "assets/images/user2.png",
  "assets/images/user3.png",
  "assets/images/user4.png",
  "assets/images/user0.png",
  "assets/images/user1.png",
  "assets/images/user2.png",
  "assets/images/user3.png",
  "assets/images/user4.png",
  "assets/images/user0.png",
  "assets/images/user1.png",
  "assets/images/user2.png",
  "assets/images/user3.png",
  "assets/images/user4.png"
];
